### ISSUE TITLE
Build scripts for equuleus and sagitta

### ISSUE THREAD

**Issue by marekm72** [kwladyka/os-builds#1]
Hello, yesterday you wrote a comment in T6264 then I replied and then both comments have been quickly removed by silencer...
Please see https://github.com/dd010101/vyos-jenkins for detailed instructions and automated scripts to build your own APT repo and ISO images, more testing is welcome, as usual be careful, this is unofficial, don't ask VyOS(tm) for support.

**Comment by kwladyka** [comment]
thank you @marekm72

**Comment by kwladyka** [comment]
For the future reference:

https://github.com/dd010101/vyos-jenkins is unofficial and only one source of knowledge how to build VyOS ISO.
VyOS team blocked access to packages and VyOS documentation to build IS is outdated.

I decided to use nightly build, because someone who I trust recommended me to use it. This versions (in his opinion) are stable, use new kernel etc. VyOS nightly builds are not beta, but more like stable not well tested versions.

What needs to be done to close this issue:
1) Figure out from https://github.com/dd010101/vyos-jenkins how to (commands) build VyOS ISO and dependency packages.
2) re-write to github actions

Then everyone can build own ISO easy in github actions for free.

As long as I use nightly build I don't invest my time to finish the job. Although if I will stop to use nightly builds for any reason, then on the first place I will consider if use VyOS at all, because of what they do.

What they did:
1) shut down slack live chat - great source of community support
2) made hard to build ISO by removing access to packages for linux which are VyOS dependency
3) didn't write in VyOS documentation how to build packages and ISO. Documentation it outdated and this doesn't work.

Technically VyOS is awesome, but it is not "open source" which you expect from open source projects.

**Comment by kwladyka** [comment]
From https://github.com/dd010101/vyos-jenkins

> The open-source era of LTS/stable branches is coming to an end. The VyOS team [already moved](https://vyos.dev/T6781) the development of LTS branches to private organization, and they will not publish the LTS/stables branches on their public GitHub anymore, the only people who can receive the copy of LTS source code are those who receive the binaries thus only those who obtain subscription.

> The only public branches will be the current and whatever branch is in the stream phase (today the circinus). Thus moving forward only those branches can be built up to date.

Which close the issue. It is not possible to build own ISO anymore.

**Comment by marekm72** [comment]
Well as https://github.com/dd010101/vyos-jenkins/commit/186556e177cdb859037d9b1fb5cdec35587f488b says - it was fun while it lasted - maybe a fork of last available sagitta will appear if there is enough interest (like VyOS was a fork of Vyatta, or XCP-NG was a fork of XenServer), if not then it's time to look for alternatives, Alpine Linux (running from RAM with LBU to save permanent changes) + ifstate + BIRD + accel-ppp looks promising.
